spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


  mvc:
    hiddenmethod:
      filter:
        enabled: true

  token:
    expiration: 86400
    secretKey:  72d8fb249e2074c49166b401ede475acee909e8e272dbcd134dcdf744f000db3
